sudo: required
dist: trusty
language: node_js
node_js:
- 8
branches:
  only:
  - master
  - staging
cache:
  directories:
    - "node_modules"
addons:
  chrome: stable
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"
before_script:
- npm install -g firebase-tools
script:
- npm run test:ci
- npm run e2e
before_deploy:
- npm run pwa
deploy:
  provider: script
  script: ./scripts/staging.sh
  on:
    branch: staging
deploy:
  provider: script
  script: ./scripts/master.sh
  on:
    branch: master
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
  slack: eventpicking:jb0vuR0xTQzpICYBCkDVEYWI