sudo: required
dist: trusty
language: node_js
node_js:
- 8
branches:
  only:
  - master
  - develop
cache:
  directories:
    - "node_modules"
addons:
  chrome: stable
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"
before_script:
- npm install -g firebase-tools
script:
- npm run test:ci
- npm run e2e
before_deploy:
- npm run pwa
deploy:
  provider: firebase
  token:
    secure: 1/MlHp9O2bdGOJUvy5Zv_tEZIJ7ZKjOWWeo8ft5A7N8xo
  on:
    branch:
      - master
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
  slack: eventpicking:jb0vuR0xTQzpICYBCkDVEYWI